image: python:3.5
before_script:
  - pip install tox
stages:
  - style
  - test

flake8:
  stage: style
  script:
    - tox -e flake8

imports:
  stage: style
  script:
    - tox -e isort

py35:
  stage: test
  script:
    - echo -e $AFIP_TEST_KEY > testapp/test.key
    - echo -e $AFIP_TEST_CRT > testapp/test.crt
    - tox -e py35
