[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "django_afip/version.py"
version_scheme = "post-release"

[tool.pytest.ini_options]
addopts = """
  --reuse-db
  --cov=django_afip
  --cov-report=term-missing:skip-covered
  --no-cov-on-fail
  --color=yes
"""
markers = [
  "live: Tests done with the live test environment."
]
DJANGO_SETTINGS_MODULE = "testapp.settings"

[tool.mypy]
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "testapp.settings"

[tool.ruff.isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]

[tool.coverage.run]
source = ["django_afip"]

[tool.ruff]
select = [
    "F",
    "E",
    "W",
    "I",
    # "N",
    "UP",
    "YTT",
    "ANN",
    "B",
    "A",
    "C4",

    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "PYI",

    "PT",
    "Q",
    "RSE",
    "RET",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "PGH",
    "PLE",
    "RUF",
]
ignore = [
  "ANN101",  # Annotation for 'self'
  "ANN002",  # Annotations for *args
  "ANN003",  # Annotations for **kwargs
  "PT004"
]
target-version = "py38"

[tool.ruff.per-file-ignores]
# Fails with auto-generated migrations. Unsolvable contradiction between ruff and mypy.
# This likely needs to be addressed in Django itself (either use an immutable
# type or annotate these fields as ClassVar)
"django_afip/migrations/0*.py"= ["RUF012"]
