[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "django_afip/version.py"
version_scheme = "post-release"

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
profile = "black"
force_single_line = true

[tool.coverage.run]
source = ["django_afip"]
