name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install tox
      - run: tox
        env:
          TOXENV: docs
