name: Tests

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7', '3.8' ]
        db: [ postgres, mysql, sqlite ]
        django: [ '22', '30', '31', '32']
    name: django-${{ matrix.django }}, python${{ matrix.python }}, ${{ matrix.db }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install tox codecov
      - run: sudo apt-get update && sudo apt-get install libpq-dev libmysqlclient-dev
      - run: tox
        env:
          TOXENV: django${{ matrix.django }}-${{ matrix.db }}
          DB: ${{ matrix.db }}
      - run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  tests-live:
    runs-on: ubuntu-latest
    name: live
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: x64
      - run: pip install tox codecov
      - run: sudo apt-get update && sudo apt-get install libpq-dev
      - run: tox
        env:
          TOXENV: live
          DB: postgres
      - run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
